Blog/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'posts#index', as: 'home'  
  
  get 'about'=>'contact#me'

  resources :posts do
    resources :comments
  end 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

Blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Blog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user  
end

Blog/app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    validates :title, presence: true, length: {minimum: 3}
    validates :content, presence: true, length: {minimum: 10}
end

Blog/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts
  has_many :comments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

Blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]  
    before_action :set_comment, only: [ :destroy]
    def new
        @comment = Comment.new

    end
    
    def create
        @post = Post.find(params[:post_id])
        @comment = current_user.comments.new(comment_params)
        @comment.post = @post
        @comment.save
        redirect_to post_path(@post)
        
    end

    def destroy 
        @comment = Comment.find(params[:id])
        @comment.destroy
        
    
    end

    private def comment_params
        params.require(:comment).permit(:content)
        
    end
    private def set_comment
       
        
    end

    
end

Blog/app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def about
        
    end
end

Blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]  
    before_action :set_post, only: [:edit, :update, :destroy]
    def index
        @posts = Post.all
    end
    def new
        @post = Post.new
    end

    def show
        @post = Post.find(params[:id])
    end     

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
            redirect_to posts_path
        else
            render 'edit'
        end
    end

    def destroy 
        @post = Post.find(params[:id])
    
        @post.destroy
        redirect_to posts_path
        
    end

    def create
        @post = Post.new(post_params)
        @post = current_user.posts.new(post_params)
        if @post.save
            redirect_to @post
        else
            render 'new'
        end
        

    end
    
    private def post_params
        params.require(:post).permit(:title, :content)        
    end
    
    private def set_post
        @post = current_user.posts.find(params[:id])        
    end
end

Blog/app/helpers/application_helper.rb
module ApplicationHelper
end

Blog/app/helpers/comments_helper.rb
module CommentsHelper
end

Blog/app/helpers/contact_helper.rb
module ContactHelper
end

Blog/app/helpers/post_helper.rb
module PostHelper
end

Blog/app/views/contact/me.html.erb
<h3>Description</h3>
<span>Here is description</span>

Blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Work</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h4 class="my-0 mr-md-auto font-weight-normal">My Blog</h4>
  <nav class="my-2 my-md-0 mr-md-3">
    <a class="p-2 text-dark" ><%=link_to "to main", home_path%></a>
     <% if user_signed_in? %>
    <a class="p-2 text-dark"><%=link_to "add",new_post_path%></a>
    <% end%>
    <a class="p-2 text-dark"><%=link_to "Author",about_path%></a>
    <% if user_signed_in? %>
    <a class="p-2 text-dark"> <%= link_to "Log out", destroy_user_session_path, :method => :delete %></a>
    <a class="p-2 text-dark"><%=current_user.email%></a>
    <% else %>
    <a class="p-2 text-dark" href="<%= new_user_registration_path%>">Sign up</a>
    <a class="p-2 text-dark" href="<%= new_user_session_path%>">Log in</a>
    <% end %>
  </nav>

  <p class="notice"><%= notice%></p>
  <p class="alert"><%= alert %></p> 

 
  </div>
  <div class='container'>
    <%= yield %>
    </div>
  </body>
</html>

Blog/app/views/posts/edit.html.erb
<h2>Edit</h2>


<%= form_for @post do |f|%>
<% if @post.errors.any?%>
    <% @post.errors.full_messages.each do |msg| %>
      <div class='alert alert-danger'><%=msg%></div>
    <% end %>
<% end %>
<p>Name</p>
<%= f.text_field(:title,{:class => 'form-control'})%>
<p>Text</p>
<br>
<br>

<%= f.text_area(:content,{:class => 'form-control'})%>
<br>
<%= f.submit({:class => 'btn btn-success'})%>
<% end%>

Blog/app/views/posts/index.html.erb
<h2>Posts</h2>
<br>
<br>
<% @posts.each do |post| %>


<div class='well'>
  <h4><%= post.title%></h4>
  <p><%= post.content%></p>
  <%= link_to "Open post", post, :class => 'btn btn-default'%>
  </div>
<% end %>

Blog/app/views/posts/new.html.erb
<h3>New post</h3>
<%= form_for :post, url: posts_path do |f|%>
<% if @post.errors.any?%>
    <% @post.errors.full_messages.each do |msg| %>
      <div class='alert alert-danger'><%=msg%></div>
    <% end %>
<% end %>
<p>Name:</p>
<br>
<%= f.text_field(:title,{:class => 'form-control'})%>
<p>Text:</p>
<%= f.text_area(:content,{:class => 'form-control'})%>
<br>
<%= f.submit({:class => 'btn btn-success'})%>
<% end%>

Blog/app/views/posts/show.html.erb
<h2><%= @post.title%></h1>
<a><strong>Author:</strong> <%= @post.user.email%></a>
<p><strong>Text:</strong><%= @post.content%></p>
<%if @post.user_id==current_user.id %>
<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-warning'%>
<%= link_to "Delete", post_path(@post), method: :delete, data: {confirm:"Are you sure?"}, :class => 'btn btn-warning'%>
<% end %>
<br>
<br>
<h3>Comments</h3>
<% @post.comments.each do |comment| %>
<div class='well'>
  <p><strong><%=  %></strong>: <%=comment.content %> 
  <%if @post.user_id==current_user.id %>
   <a><%= link_to "X", post_comment_path(@post, comment),method: :delete, data: {confirm:"Are you sure?"} %></a><% end %> </p> 
   <% end %>
  </div> 
<%= form_for([@post, @post.comments.build]) do |f|%>
<% if @post.errors.any?%>
    <% @post.errors.full_messages.each do |msg| %>
      <div class='alert alert-danger'><%=msg%></div>
    <% end %>
<% end %>
<p>Comment</p>
<%= f.text_area(:content,{:class => 'form-control'})%>
<br>
<%= f.submit({:class => 'btn btn-success'})%>
<% end%>